### ISSUE TITLE
Error' installing 

### ISSUE THREAD

**Issue by dalpan** [effortlessdevsec/ninjasworkout#3]
I got an error message like this,

> root@LAPTOP-8MMMLVHA:/home/van/SSRFire/ninjasworkout# npm i
> npm WARN vulnerable-app@1.0.0 No repository field.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 
> audited 333 packages in 1.683s
> 
> 28 packages are looking for funding
>   run `npm fund` for details
> 
> found 17 vulnerabilities (2 low, 7 moderate, 6 high, 2 critical)
>   run `npm audit fix` to fix them, or `npm audit` for details
> root@LAPTOP-8MMMLVHA:/home/van/SSRFire/ninjasworkout# node app.js
> /home/van/SSRFire/ninjasworkout/node_modules/whatwg-url/dist/encoding.js:2
> const utf8Encoder = new TextEncoder();
>                     ^
> 
> ReferenceError: TextEncoder is not defined
>     at Object.<anonymous> (/home/van/SSRFire/ninjasworkout/node_modules/whatwg-url/dist/encoding.js:2:21)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Module.require (internal/modules/cjs/loader.js:692:17)
>     at require (internal/modules/cjs/helpers.js:25:18)
>     at Object.<anonymous> (/home/van/SSRFire/ninjasworkout/node_modules/whatwg-url/dist/url-state-machine.js:5:34)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
> root@LAPTOP-8MMMLVHA:/home/van/SSRFire/ninjasworkout#

How do I fix it?

**Comment by cybersafeblr** [comment]
Open this file in a text editor 'node_modules/whatwg-url/dist/encoding.js'
at the top of the file after "use strict" add this line

`const { TextEncoder, TextDecoder } = require("util");`
